### PR TITLE
Add an #xml method that switches between Nokogiri parsers

### PR DESCRIPTION
**Pull request by jalada**
So you can 'scrape' XML as well as HTML (e.g. RSS feeds).

I'm sorry, I haven't added any specs... :(

### CODE REVIEW

**Comment by sathish316** [comment]
I don't see the value of scraping XML feed unless it is used to transform input XML. Any library which parses XML from url should be able to do this.

However, converting scraped data to XML like Jsonify would be much more useful. See #31 for more details

**Comment by jalada** [comment]
I guess for me..I am scraping a mixture of HTML and XML using Scrapify in a single app, and it's nice to have it all working the same way.

**Comment by sathish316** [comment]
Does it involve transforming the XML/RSS feed vastly different from the original feed? Do you see any use for this as an XML to JSON converter?

**Comment by jalada** [comment]
Closing as project looks abandoned

**Pull request closed without merging**
